[[ $- != *i* ]] && return

shopt -s completion_strip_exe

if [ -f /etc/profile.d/git-prompt.sh ]; then
    . /etc/profile.d/git-prompt.sh
fi

GIT_PS1_SHOWDIRTYSTATE=true
GIT_PS1_SHOWUNTRACKEDFILES=true
GIT_PS1_SHOWUPSTREAM="auto"
GIT_PS1_SHOWCOLORHINTS=true
GIT_PS1_SHOWSTASHSTATE=true

export HISTFILESIZE=9000
export HISTSIZE=500
export HISTCONTROL=ignoredups:ignorespace
export HISTIGNORE="ls:cd:pwd:exit:clear:history:df:du:git status:git diff:git log"
export HISTTIMEFORMAT="%F %T "

# Alias
alias cp="cp -i"
alias mv="mv -i"
alias rm="rm -i"
alias df="df -Th"
alias du="du -sh"
alias less="less -r"
alias grep="grep --color=auto"
{{#if (is_executable "eza")}}
alias ls="eza --color=auto"
alias l="eza -F --color=auto"
alias la="eza -a --color=auto"
alias ll="eza -ahl --color=auto --time-style long-iso"
{{else}}
alias ls="ls --color=auto"
alias l="ls -F --color=auto"
alias la="ls -a --color=auto"
alias ll="ls -alhF --color=auto"
{{/if}}

eval "$(fzf --bash)"
